name: Test Setup Only

# This workflow just tests the environment setup without running the actual model training
# Useful for debugging CI setup issues

on:
  workflow_dispatch:

jobs:
  test-environment-setup:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.11"]  # Limited set for quick testing
    
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: Create virtual environment
        run: python -m venv test-venv
      
      - name: Activate venv and install prerequisites (Linux)
        if: runner.os == 'Linux'
        run: |
          source test-venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r prerequisites/requirements.txt
          echo "Environment setup completed successfully!"
          python -c "import torch; print(f'PyTorch: {torch.__version__}')"
          python -c "import transformers; print(f'Transformers: {transformers.__version__}')"
      
      - name: Activate venv and install prerequisites (Windows)
        if: runner.os == 'Windows'
        run: |
          .\test-venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install -r prerequisites/requirements.txt
          Write-Host "Environment setup completed successfully!"
          python -c "import torch; print(f'PyTorch: {torch.__version__}')"
          python -c "import transformers; print(f'Transformers: {transformers.__version__}')"
        shell: pwsh
